# Generated by Django 3.1 on 2020-08-23 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20200822_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='set_url_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hits', to='api.seturl'),
        ),
        migrations.AlterField(
            model_name='seturl',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='set_url', to='api.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
