# Generated by Django 3.1 on 2020-08-24 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20200823_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seturl',
            name='deleted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='seturl',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='set_url', to=settings.AUTH_USER_MODEL),
        ),
    ]
