# Generated by Django 3.1 on 2020-08-25 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20200825_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seturl',
            name='user_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set_url', to=settings.AUTH_USER_MODEL),
        ),
    ]
