# Generated by Django 3.1 on 2020-08-27 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200825_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='agent_client',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='country_code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='http_reffer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='ip',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='lattitude',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='longitude',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='region_code',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='seturl',
            name='short_url',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
