# Generated by Django 3.1 on 2020-08-30 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200827_0113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hit',
            old_name='lattitude',
            new_name='latitude',
        ),
    ]
