# Generated by Django 3.1 on 2020-08-30 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200830_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Is_developer',
            field=models.BooleanField(default=False, null=True, verbose_name='Is_developer'),
        ),
    ]
