# Generated by Django 3.1 on 2020-08-28 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0007_auto_20190111_0542'),
        ('authKnox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenprofile',
            name='authToken',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_profile', to='knox.authtoken', unique=True),
        ),
    ]
