# Generated by Django 3.1 on 2020-08-28 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knox', '0007_auto_20190111_0542'),
        ('authKnox', '0002_auto_20200828_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenprofile',
            name='authToken',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_profile', to='knox.authtoken'),
        ),
    ]
