# Generated by Django 3.1 on 2020-08-28 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authKnox', '0003_auto_20200828_0556'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenProfile',
        ),
    ]
