# Generated by Django 3.1 on 2020-08-29 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knox', '0007_auto_20190111_0542'),
        ('authKnox', '0004_delete_tokenprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_token', models.CharField(max_length=100)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_profile', to='knox.authtoken')),
            ],
            options={
                'ordering': ('name_token',),
            },
        ),
    ]
