# Generated by Django 3.1 on 2020-08-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authKnox', '0005_tokenprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tokenprofile',
            options={'ordering': ('Host',)},
        ),
        migrations.RemoveField(
            model_name='tokenprofile',
            name='name_token',
        ),
        migrations.AddField(
            model_name='tokenprofile',
            name='Cookie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tokenprofile',
            name='Host',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tokenprofile',
            name='user_agent',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
