# Generated by Django 3.1 on 2020-09-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authKnox', '0008_auto_20200912_0232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenprofile',
            name='Cookie',
        ),
        migrations.AddField(
            model_name='tokenprofile',
            name='name_token',
            field=models.CharField(default='unknown', max_length=1000, null=True),
        ),
    ]
