# Generated by Django 3.1 on 2020-09-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authKnox', '0009_auto_20200912_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenprofile',
            name='name_token',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
